# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dedbf837bb158d187906130c5f1eaf7abf47953119d30997bbdb7f8b25f81c5b6e5c01553b9a4673d4274565d619dd1873964a11e7865388898284775a062cb8

test:
  secret_key_base: 73f41b608a6fcb1b328926890fa4d477de90af29b332c32a7dfb3ab7158298f85c9d8eb6ed8ab06467d8573abc52929dff3e3ff1eeb9d8cbc2e5633da9482927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
